### ISSUE TITLE
README error: src/config.js is not a valid path

### ISSUE THREAD

**Issue by I-ARao** [techcsispit/Weather#1]
Aditi Rao, 2022200003

- Per the README, we were to obtain an OpenWeather API key and add it to config.js in the src folder. 

![issue_1](https://github.com/techcsispit/Weather/assets/118061722/439724df-fac8-4ee0-ac22-7bc6ff55b710)

- However, no such file exists.

![issue_2](https://github.com/techcsispit/Weather/assets/118061722/53fa6798-45fc-454b-a860-10e9a4888442)

- The API key is, instead, mentioned in the components folder in Tempdata.js, in the form of a URL.

![image](https://github.com/techcsispit/Weather/assets/118061722/4b703456-5cf4-4657-bee4-3f6d77d86d7d)

Please make note of this issue and approve the pull request made to correct the README.

**Comment by techcsispit** [comment]
Yup go ahead and fix it
