### ISSUE TITLE
feature update: background change according to city

### ISSUE THREAD

**Issue by mansidhamne** [techcsispit/Weather#16]
**Feature Details:**

**Interesting Backgrounds**: The background will change as per the city entered. For example if its Mumbai, the background will display images that resonate with Mumbai like Gateway of India or the skyline.

**Improved User Experience:** The catchy and unique backgrounds will add on the user experience.

I would like to request that you reserve this feature implementation for me.

**Comment by Saachi30** [comment]
Assigned to you!!
