### ISSUE TITLE
DEPRECATED Packages in Dependencies

### ISSUE THREAD

**Issue by I-ARao** [techcsispit/Weather#4]
Aditi Rao, 2022200003

- While installing dependencies, the system threw up some warnings about deprecated packages. 

![image](https://github.com/techcsispit/Weather/assets/118061722/ed118c23-2f7f-4f71-b0d8-c72c5f1002d3)

- It highlighted 10 vulnerabilities, 1 of which was labelled *critical*

![image](https://github.com/techcsispit/Weather/assets/118061722/4f5e33c3-f2de-4925-9a6e-53831ee2c975)

**Comment by techcsispit** [comment]
Yup, resolve it
